In [8]:
import numpy as np
import matplotlib.pyplot as plt
from svd import ApproxSVD
from scipy.sparse.linalg import svds
import tests

In [9]:
np.random.seed(42)
random_matrix = np.random.rand(4, 12)

print(random_matrix)

[[0.3745 0.9507 0.732  0.5987 0.156  0.156  0.0581 0.8662 0.6011 0.7081 0.0206 0.9699]
 [0.8324 0.2123 0.1818 0.1834 0.3042 0.5248 0.4319 0.2912 0.6119 0.1395 0.2921 0.3664]
 [0.4561 0.7852 0.1997 0.5142 0.5924 0.0465 0.6075 0.1705 0.0651 0.9489 0.9656 0.8084]
 [0.3046 0.0977 0.6842 0.4402 0.122  0.4952 0.0344 0.9093 0.2588 0.6625 0.3117 0.5201]]


In [10]:
p = 3
u, s, vt = np.linalg.svd(random_matrix)
print(u)

[[-0.6077  0.4448 -0.3508 -0.5566]
 [-0.3444 -0.0607  0.9048 -0.2429]
 [-0.5588 -0.7862 -0.2311  0.1276]
 [-0.4471  0.4248  0.0688  0.7842]]


In [15]:
approx_svd = ApproxSVD(10, p, True)
traces, ubar, x_approx = approx_svd.fit(random_matrix)

# plt.plot(traces, label='Data')
# aux = u.transpose() @ random_matrix @ vt.transpose()
# true_energy = np.trace(aux[:p, :p])

# plt.axhline(y=true_energy, color='red', linestyle='dotted', linewidth=2, label='Real U trace')
# plt.ylim(bottom=min(0, traces.min()))
# plt.xlabel('Index')
# plt.ylabel('Trace')
# plt.title('Trace progression vs real U trace')
# plt.legend()
# plt.show()

DEBUG - Time: 0.001 seconds for initial scores
DEBUG - Time: 0.000 seconds for find max score
DEBUG - Time: 0.000 seconds for perform matrix mul
DEBUG - Time: 0.001 seconds for update scores
DEBUG - Time: 0.000 seconds for find max score
DEBUG - Time: 0.000 seconds for perform matrix mul
DEBUG - Time: 0.001 seconds for update scores
DEBUG - Time: 0.000 seconds for find max score
DEBUG - Time: 0.000 seconds for perform matrix mul
DEBUG - Time: 0.000 seconds for update scores
DEBUG - Time: 0.000 seconds for find max score
DEBUG - Time: 0.000 seconds for perform matrix mul
DEBUG - Time: 0.001 seconds for update scores
DEBUG - Time: 0.000 seconds for find max score
DEBUG - Time: 0.000 seconds for perform matrix mul
DEBUG - Time: 0.000 seconds for update scores
DEBUG - Time: 0.000 seconds for find max score
DEBUG - Time: 0.000 seconds for perform matrix mul
DEBUG - Time: 0.001 seconds for update scores
DEBUG - Time: 0.000 seconds for find max score
DEBUG - Time: 0.000 seconds for perform ma

In [ ]:
# ubar projection
print(ubar[:p, :] @ random_matrix)
print()
# true u projection
print(u[:p, :] @ random_matrix)


[[-0.4649 -0.1557 -0.8453 -0.2123]
 [-0.3466 -0.8405  0.3852 -0.1583]
 [-0.7008  0.519   0.3703 -0.3201]]

[[-0.6077  0.4448 -0.3508 -0.5566]
 [-0.3444 -0.0607  0.9048 -0.2429]
 [-0.5588 -0.7862 -0.2311  0.1276]]


In [13]:
tests.run_tests()

0.04632260994098658

0.0070977350871981315

0.01579533408203737

0.0010695179793689391

0.0011217188743213313

0.027401990204570126

0.000367782705589903

6.895103858539642e-06

0.0002511481322073905

0.0006559097356682031



# Validate Ubar
Extract mean from random matrix (to center it) and then project it with Ubar to functionally perform PCA (not sure)

In [1]:
from sklearn.decomposition import PCA
random_mean = np.mean(random_matrix, axis=1, keepdims=True)
random_centered = random_matrix - random_mean
_, ubar, _ = svd.approx_svd(random_centered, p, 200)
random_transposed = random_centered.transpose()

# PCA to 3 components
pca = PCA(n_components=3)
X_pca = pca.fit_transform(random_transposed)

print(ubar[:p, :] @ random_centered)
print()
print(u[:p, :] @ random_matrix)
print()
print(X_pca.transpose())
print(np.linalg.norm(ubar[:p, :] @ random_matrix, 'fro'))
print(np.linalg.norm(u[:p, :] @ random_matrix, 'fro'))

KeyboardInterrupt: 